packages:
  - apps/*
  - packages/*

# ADD THIS BLOCK
allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  deno: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - events.vex@7.0.0
