-- Reconcile drift: gen_random_uuid() defaults were applied outside migration history.
-- Team IDs are generated by Prisma (@default(uuid())); Invite IDs are explicit invite codes.
ALTER TABLE "Team" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Invite" ALTER COLUMN "id" DROP DEFAULT;
