// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import { normalizeDatabaseUrl } from "./src/normalize-database-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Direct connection for CLI (migrate, db push). Runtime uses DATABASE_URL via the pg adapter.
    url: normalizeDatabaseUrl(env("DIRECT_URL")),
  },
});
